version: '3.8'

services:
  # The Brains
  api:
    build: 
      context: .
      dockerfile: apps/api/Dockerfile
    restart: always
    environment:
      - DATABASE_URL=postgres://cherry:cherry@db:5432/cherry
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    depends_on:
      - db
    networks:
      - cherry-net

  # The Face
  dashboard:
    build:
      context: .
      dockerfile: apps/dashboard/Dockerfile
    restart: always
    ports:
      - "3000:3000" # User accesses this
    environment:
      # Server-side internal networking to API
      - NUXT_API_URL=http://api:3000
    depends_on:
      - api
    networks:
      - cherry-net

  db:
    image: postgres:16-alpine
    volumes:
      - cherry_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=cherry
      - POSTGRES_PASSWORD=cherry
      - POSTGRES_DB=cherry
    networks:
      - cherry-net

volumes:
  cherry_data:

networks:
  cherry-net: