services:
  postgres:
    image: postgres:18-alpine
    container_name: cherry_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: cherry_user
      POSTGRES_PASSWORD: cherry_password
      POSTGRES_DB: cherry_local
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
